name:                storepats
version:             0.1.0.0
github:              "mgsloan/storepats"
license:             BSD3
author:              "Michael Sloan"
maintainer:          "mgsloan@gmail.com"
copyright:           "2019 Michael Sloan"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/mgsloan/storepats#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- template-haskell

library:
  source-dirs: src

ghc-options:
- -Wall

tests:
  storepats-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - storepats
